// Compile lib/engine/gemm.wat into an inlined base64 module (lib/engine/gemm-wasm.ts).
import { readFileSync, writeFileSync } from 'node:fs';
import wabtFactory from 'wabt';

const root = new URL('..', import.meta.url).pathname;
const wabt = await wabtFactory();
const source = readFileSync(`${root}lib/engine/gemm.wat`, 'utf8');
const parsed = wabt.parseWat('gemm.wat', source, { simd: true });
parsed.validate();
const { buffer } = parsed.toBinary({});
const base64 = Buffer.from(buffer).toString('base64');
writeFileSync(
  `${root}lib/engine/gemm-wasm.ts`,
  `// Generated by scripts/build-wasm.mjs from gemm.wat. Do not edit.\nexport const GEMM_WASM_BASE64 =\n  '${base64}';\n`,
);
console.log(`wrote gemm-wasm.ts (${buffer.length} bytes)`);
